export const Events = {
  VIDEO_BITRATE_CHANGED: "videoRepresentationChange",
  AUDIO_BITRATE_CHANGED: "audioBitrateChange",
  FORCE_VIDEO_BITRATE_CHANGE: "forceVideoBitrateChange",
  REPRESENTATIONS_CHANGED: "representationsChanged",
  ENABLE_ABR: "enableAbr",
  BUFFER_LEVEL_UPDATED: "bufferLevelUpdated",
  BUFFER_EMPTY: "bufferEmpty",
  QUALITY_CHANGE_REQUESTED: "qualityChangeRequsted",
  TOGGLE_PLAYBACK_REQUESTED: "togglePlaybackRequested",
  SEEK_REQUESTED: "seekRequested",
  TOGGLE_FULLSCREEN_REQUEST: "toggleFullscreenRequest",
  VIDEO_CLICKED: "videoClicked",
  PLAYBACK_RATE_REQUESTED: "playbackRateRequested",
  BUFFER_ERROR: "bufferError",
  FRAGMENT_LOADING_COMPLETED: "fragmentLoadingCompleted",
  FREEZE_LOGGING: "freezeLogging",
  SHOW_PERSISTENT_PLAY_BUTTON: "showPersistenPlayBtn",
  FRAGMENT_LOADING_STARTED: "fragmentLoadingStarted",
  MANIFEST_PARSED: "manifestParsed",
  KEEP_UI_VISIBLE: "keepUiVisible",
  HIDE_UI_WITH_DELEAY: "hideUiWithDelay",
  RESTART_VIDEO_REQUESTED: "restartVideoRequested",
  BUFFER_TARGET_CHANGED: "bufferTargetChanged",
  MOBILE_SETTINGS_MENU_OPENED: "mobileSettingsMenuOpened",
};
